; ****************************************************************************
; FAT32 seek / extent map test (runs in the QNICE emulator in batch mode)
;
; Table-driven: T_TABLE (generated by gen.py) holds 5-word records
;   op 1 OPEN  a = file index
;   op 2 SEEK  a/b = position LO/HI, c = bytes to read and verify, d = error
;   op 3 SEEKM like SEEK, but FAT32$FILE_SEEK_MAP with the current map
;   op 4 MAP   a = map buffer size (words), b = expected error, c = extents
;   op 5 WRITE a/b = position, c = length: write the inverted pattern, read it
;              back, write the pattern again, read it back
;   op 6 STATS a = label: print and reset the SD block read counter
;   op 0 END
; Every byte read is compared with the file pattern: byte p of a file is
; byte (p % 4) of the big-endian 32-bit value p / 4.
; ****************************************************************************

TEST_MAIN       AND     0x00FF, SR
                MOVE    VAR$STACK_START, SP
                MOVE    T_S_HELLO, R8
                RSUB    IO$PUTS, 1

                MOVE    _SD$DEVICEHANDLE, R8
                MOVE    1, R9
                RSUB    FAT32$MOUNT_SD, 1
                CMP     0, R9
                RBRA    T_MOUNTED, Z
                MOVE    T_S_MNTERR, R8
                RSUB    IO$PUTS, 1
                MOVE    R9, R8
                RSUB    IO$PUT_W_HEX, 1
                HALT

                ; count the SD block reads by hooking the device function
T_MOUNTED       MOVE    _SD$DEVICEHANDLE, R8
                ADD     FAT32$DEV_BLOCK_READ, R8
                MOVE    T_ORIG_RD, R9
                MOVE    @R8, @R9
                MOVE    T_COUNT_RD, @R8

                MOVE    T_TABLE, R0             ; R0: table pointer
                XOR     R6, R6                  ; R6: failures
                XOR     R7, R7                  ; R7: record number
                RSUB    T_CSUM, 1               ; check: reference checksum
                MOVE    T_SAVE_CS, R9
                MOVE    R8, @R9
                MOVE    T_SAVE_R0, R8           ; check
                MOVE    R0, @R8
                MOVE    T_SAVE_R7, R8
                MOVE    R7, @R8

T_LOOP          MOVE    SR, R8                  ; check: still in bank 0?
                AND     0xFF00, R8
                RBRA    T_LOOP_OK, Z
                MOVE    T_S_BANK, R8
                RSUB    IO$PUTS, 1
                MOVE    SR, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    SP, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    T_RECNO, R8
                MOVE    @R8, R8
                RSUB    IO$PUT_W_HEX, 1
                HALT
T_LOOP_OK       MOVE    T_SAVE_R0, R8           ; check: registers intact?
                CMP     @R8, R0
                RBRA    T_REGS_BAD, !Z
                MOVE    T_SAVE_R7, R8
                CMP     @R8, R7
                RBRA    T_REGS_OK, Z
T_REGS_BAD      MOVE    T_S_REGS, R8
                RSUB    IO$PUTS, 1
                MOVE    T_RECNO, R8
                MOVE    @R8, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    R0, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    R7, R8
                RSUB    IO$PUT_W_HEX, 1
                HALT
T_REGS_OK       RSUB    T_CSUM, 1               ; check: table intact?
                MOVE    T_SAVE_CS, R9
                CMP     @R9, R8
                RBRA    T_CS_OK, Z
                MOVE    T_S_CSUM, R8
                RSUB    IO$PUTS, 1
                MOVE    T_RECNO, R8
                MOVE    @R8, R8
                RSUB    IO$PUT_W_HEX, 1
                HALT
T_CS_OK         MOVE    @R0++, R1               ; R1: op
                MOVE    @R0++, R2               ; R2..R5: a, b, c, d
                MOVE    @R0++, R3
                MOVE    @R0++, R4
                MOVE    @R0++, R5
                ADD     1, R7
                MOVE    T_RECNO, R8
                MOVE    R7, @R8
                MOVE    T_SAVE_R0, R8           ; check
                MOVE    R0, @R8
                MOVE    T_SAVE_R7, R8
                MOVE    R7, @R8

                CMP     0, R1
                RBRA    T_END, Z
                CMP     1, R1
                RBRA    T_OPEN, Z
                CMP     2, R1
                RBRA    T_SEEK, Z
                CMP     3, R1
                RBRA    T_SEEK, Z
                CMP     4, R1
                RBRA    T_MAP, Z
                CMP     5, R1
                RBRA    T_WRITE, Z
                CMP     6, R1
                RBRA    T_STATS, Z
                MOVE    T_S_BADOP, R8
                RSUB    IO$PUTS, 1
                MOVE    R1, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    R7, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    R0, R8
                RSUB    IO$PUT_W_HEX, 1
                HALT

                ; ---- OPEN ------------------------------------------------
T_OPEN          MOVE    T_NAMES, R8
                ADD     R2, R8
                MOVE    @R8, R10                ; R10: file name
                MOVE    _SD$DEVICEHANDLE, R8
                MOVE    T_FDH, R9
                XOR     R11, R11
                RSUB    FAT32$FILE_OPEN, 1
                CMP     0, R10
                RBRA    T_LOOP, Z
                MOVE    R10, R8                 ; got
                XOR     R9, R9                  ; expected
                RSUB    T_FAIL, 1
                ADD     1, R6
                RBRA    T_LOOP, 1

                ; ---- SEEK / SEEKM ----------------------------------------
T_SEEK          MOVE    T_FDH, R8
                MOVE    R2, R9
                MOVE    R3, R10
                CMP     3, R1
                RBRA    T_SEEK_M, Z
                RSUB    FAT32$FILE_SEEK, 1
                RBRA    T_SEEK_CHK, 1
T_SEEK_M        MOVE    T_MAPBUF, R11
                RSUB    FAT32$FILE_SEEK_MAP, 1
T_SEEK_CHK      CMP     R5, R9
                RBRA    T_SEEK_OK, Z
                MOVE    R9, R8                  ; got
                MOVE    R5, R9                  ; expected
                RSUB    T_FAIL, 1
                ADD     1, R6
                RBRA    T_LOOP, 1
T_SEEK_OK       CMP     0, R9
                RBRA    T_LOOP, !Z              ; expected error: done
                MOVE    R2, R8
                MOVE    R3, R9
                MOVE    R4, R10
                XOR     R11, R11                ; pattern
                RSUB    T_VERIFY, 1
                ADD     R8, R6
                RBRA    T_LOOP, 1

                ; ---- MAP -------------------------------------------------
T_MAP           MOVE    T_FDH, R8
                MOVE    T_MAPBUF, R9
                MOVE    R2, R10
                RSUB    FAT32$FILE_MAP, 1
                CMP     R3, R9
                RBRA    T_MAP_N, Z
                MOVE    R9, R8
                MOVE    R3, R9
                RSUB    T_FAIL, 1
                ADD     1, R6
                RBRA    T_LOOP, 1
T_MAP_N         CMP     0xFFFF, R4              ; 0xFFFF: do not check
                RBRA    T_LOOP, Z
                CMP     R4, R10                 ; number of extents
                RBRA    T_MAP_P, Z
                MOVE    R10, R8
                MOVE    R4, R9
                RSUB    T_FAIL, 1
                ADD     1, R6
                RBRA    T_LOOP, 1
T_MAP_P         MOVE    T_S_EXT, R8             ; print the extent count
                RSUB    IO$PUTS, 1
                MOVE    R10, R8
                RSUB    IO$PUT_W_HEX, 1
                RSUB    IO$PUT_CRLF, 1
                RBRA    T_LOOP, 1

                ; ---- WRITE -----------------------------------------------
T_WRITE         MOVE    1, R11                  ; inverted pattern
                RSUB    T_WRITE_PASS, 1
                ADD     R8, R6
                XOR     R11, R11                ; restore the pattern
                RSUB    T_WRITE_PASS, 1
                ADD     R8, R6
                RBRA    T_LOOP, 1

                ; ---- STATS -----------------------------------------------
T_STATS         MOVE    T_S_STATS, R8
                RSUB    IO$PUTS, 1
                MOVE    R2, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    T_S_READS, R8
                RSUB    IO$PUTS, 1
                MOVE    T_READS, R8
                MOVE    @R8, R8
                RSUB    IO$PUT_W_HEX, 1
                RSUB    IO$PUT_CRLF, 1
                MOVE    T_READS, R8
                MOVE    0, @R8
                RBRA    T_LOOP, 1

                ; ---- END -------------------------------------------------
T_END           MOVE    T_S_RECS, R8
                RSUB    IO$PUTS, 1
                MOVE    R7, R8
                RSUB    IO$PUT_W_HEX, 1
                RSUB    IO$PUT_CRLF, 1
                CMP     0, R6
                RBRA    T_END_FAIL, !Z
                MOVE    T_S_PASS, R8
                RSUB    IO$PUTS, 1
                HALT
T_END_FAIL      MOVE    T_S_FAILED, R8
                RSUB    IO$PUTS, 1
                MOVE    R6, R8
                RSUB    IO$PUT_W_HEX, 1
                RSUB    IO$PUT_CRLF, 1
                HALT

; ----------------------------------------------------------------------------
; T_WRITE_PASS: seek to a/b (R2/R3), write c (R4) bytes of the pattern
; (R11 = 0) or the inverted pattern (R11 = 1), flush, seek back, verify
; Output: R8 = number of failures
; Called from the main loop, so R2..R4 are the main loop's registers: use a
; new bank only after reading them.
; ----------------------------------------------------------------------------
T_WRITE_PASS    MOVE    R2, R8
                MOVE    R3, R9
                MOVE    R4, R10
                INCRB
                MOVE    R8, R0                  ; R1|R0: position
                MOVE    R9, R1
                MOVE    R10, R2                 ; R2: length
                MOVE    R11, R3                 ; R3: mode
                XOR     R4, R4                  ; R4: failures

                MOVE    T_FDH, R8
                MOVE    R0, R9
                MOVE    R1, R10
                RSUB    FAT32$FILE_SEEK, 1
                CMP     0, R9
                RBRA    T_WP_W, Z
                MOVE    R9, R8
                XOR     R9, R9
                RSUB    T_FAIL, 1
                ADD     1, R4
                RBRA    T_WP_RET, 1

T_WP_W          MOVE    R0, R5                  ; R6|R5: running position
                MOVE    R1, R6
                MOVE    R2, R7                  ; R7: remaining
T_WP_WLOOP      CMP     0, R7
                RBRA    T_WP_FLUSH, Z
                MOVE    R5, R8
                MOVE    R6, R9
                RSUB    T_EXPECT, 1             ; R10: pattern byte
                CMP     0, R3
                RBRA    T_WP_WB, Z
                XOR     0x00FF, R10
T_WP_WB         MOVE    T_FDH, R8
                MOVE    R10, R9
                RSUB    FAT32$FILE_WB, 1
                CMP     0, R9
                RBRA    T_WP_WNEXT, Z
                MOVE    R9, R8
                XOR     R9, R9
                RSUB    T_FAIL, 1
                ADD     1, R4
                RBRA    T_WP_RET, 1
T_WP_WNEXT      ADD     1, R5
                ADDC    0, R6
                SUB     1, R7
                RBRA    T_WP_WLOOP, 1

T_WP_FLUSH      MOVE    T_FDH, R8
                RSUB    FAT32$FLUSH, 1
                MOVE    T_FDH, R8               ; seek back and verify
                MOVE    R0, R9
                MOVE    R1, R10
                RSUB    FAT32$FILE_SEEK, 1
                MOVE    R0, R8
                MOVE    R1, R9
                MOVE    R2, R10
                MOVE    R3, R11
                RSUB    T_VERIFY, 1
                ADD     R8, R4

T_WP_RET        MOVE    R4, R8
                DECRB
                RET

; ----------------------------------------------------------------------------
; T_VERIFY: read R10 bytes from the current position of T_FDH and compare
; them with the pattern of position R9|R8 (R11 = 1: inverted pattern).
; Reading at the end of the file must return FAT32$EOF.
; Output: R8 = number of failures (at most 1: stops at the first one)
; ----------------------------------------------------------------------------
T_VERIFY        INCRB
                MOVE    R8, R0                  ; R1|R0: position
                MOVE    R9, R1
                MOVE    R10, R2                 ; R2: remaining
                MOVE    R11, R3                 ; R3: mode
                XOR     R4, R4                  ; R4: failures
                MOVE    T_FDH, R5
                ADD     FAT32$FDH_SIZE_LO, R5
                MOVE    @R5++, R6               ; R7|R6: file size
                MOVE    @R5, R7

T_V_LOOP        CMP     0, R2
                RBRA    T_V_RET, Z
                MOVE    T_FDH, R8
                RSUB    FAT32$FILE_RB, 1        ; R9 byte, R10 status
                CMP     R0, R6                  ; position == size?
                RBRA    T_V_DATA, !Z
                CMP     R1, R7
                RBRA    T_V_DATA, !Z
                CMP     FAT32$EOF, R10          ; must be EOF
                RBRA    T_V_RET, Z
                MOVE    R10, R8
                MOVE    FAT32$EOF, R9
                RBRA    T_V_BAD, 1
T_V_DATA        CMP     0, R10
                RBRA    T_V_CMP, Z
                MOVE    R10, R8
                XOR     R9, R9
                RBRA    T_V_BAD, 1
T_V_CMP         MOVE    R9, R5                  ; R5: byte that was read
                MOVE    R0, R8
                MOVE    R1, R9
                RSUB    T_EXPECT, 1
                CMP     0, R3
                RBRA    T_V_CMP2, Z
                XOR     0x00FF, R10
T_V_CMP2        CMP     R5, R10
                RBRA    T_V_NEXT, Z
                MOVE    T_FAILPOS, R8           ; remember where
                MOVE    R0, @R8++
                MOVE    R1, @R8
                MOVE    R5, R8
                MOVE    R10, R9
                RBRA    T_V_BAD, 1
T_V_NEXT        ADD     1, R0
                ADDC    0, R1
                SUB     1, R2
                RBRA    T_V_LOOP, 1

T_V_BAD         RSUB    T_FAIL, 1
                MOVE    1, R4
T_V_RET         MOVE    R4, R8
                DECRB
                RET

; ----------------------------------------------------------------------------
; T_CSUM: R8 = sum over the whole table (TRACE)
; ----------------------------------------------------------------------------
T_CSUM          INCRB
                XOR     R0, R0                  ; code: 0x0000 .. T_CSUM
                XOR     R1, R1
T_CS_CODE       ADD     @R0++, R1
                CMP     T_CSUM, R0
                RBRA    T_CS_CODE, !Z
                MOVE    T_TABLE, R0
T_CS_LOOP       MOVE    @R0, R2                 ; op of this record
                ADD     @R0++, R1
                ADD     @R0++, R1
                ADD     @R0++, R1
                ADD     @R0++, R1
                ADD     @R0++, R1
                CMP     0, R2
                RBRA    T_CS_LOOP, !Z
                MOVE    R1, R8
                DECRB
                RET

; ----------------------------------------------------------------------------
; T_EXPECT: pattern byte at position R9|R8 -> R10
; ----------------------------------------------------------------------------
T_EXPECT        INCRB
                MOVE    R8, R2                  ; R3|R2 = position >> 2
                SHR     2, R2
                AND     0x3FFF, R2
                MOVE    R9, R3
                SHL     14, R3
                AND     0xC000, R3
                OR      R3, R2
                MOVE    R9, R3
                SHR     2, R3
                AND     0x3FFF, R3
                MOVE    R8, R4
                AND     3, R4
                CMP     0, R4
                RBRA    T_E_1, !Z
                SWAP    R3, R10
                RBRA    T_E_RET, 1
T_E_1           CMP     1, R4
                RBRA    T_E_2, !Z
                MOVE    R3, R10
                RBRA    T_E_RET, 1
T_E_2           CMP     2, R4
                RBRA    T_E_3, !Z
                SWAP    R2, R10
                RBRA    T_E_RET, 1
T_E_3           MOVE    R2, R10
T_E_RET         AND     0x00FF, R10
                DECRB
                RET

; ----------------------------------------------------------------------------
; T_FAIL: print "FAIL rec <n> got <R8> exp <R9> pos <failpos>"
; (the first 30 failures only)
; ----------------------------------------------------------------------------
T_FAIL          INCRB
                MOVE    R8, R0
                MOVE    R9, R1
                MOVE    T_NFAIL, R2
                ADD     1, @R2
                CMP     30, @R2
                RBRA    T_F_PRINT, N            ; 30 > count: print
                RBRA    T_F_RET, 1
T_F_PRINT       MOVE    T_S_FAIL, R8
                RSUB    IO$PUTS, 1
                MOVE    T_RECNO, R8
                MOVE    @R8, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    T_S_GOT, R8
                RSUB    IO$PUTS, 1
                MOVE    R0, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    T_S_EXP, R8
                RSUB    IO$PUTS, 1
                MOVE    R1, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    T_S_POS, R8
                RSUB    IO$PUTS, 1
                MOVE    T_FAILPOS, R2
                MOVE    @R2++, R3
                MOVE    @R2, R8
                RSUB    IO$PUT_W_HEX, 1
                MOVE    R3, R8
                RSUB    IO$PUT_W_HEX, 1
                RSUB    IO$PUT_CRLF, 1
T_F_RET         DECRB
                RET

; ----------------------------------------------------------------------------
; T_COUNT_RD: hooked device "block read" function, counts and forwards
; ----------------------------------------------------------------------------
T_COUNT_RD      INCRB
                MOVE    T_READS, R0
                ADD     1, @R0
                MOVE    T_ORIG_RD, R0
                ASUB    @R0, 1
                DECRB
                RET

T_S_HELLO       .ASCII_W "FAT32 seek test\n"
T_S_MNTERR      .ASCII_W "mount error "
T_S_BADOP       .ASCII_W "bad op\n"
T_S_REGS        .ASCII_W "REGS CHANGED: last record, R0, R7: "
T_S_CSUM        .ASCII_W "TABLE CORRUPTED after record "
T_S_BANK        .ASCII_W "BANK CHANGED: SR, last record "
T_S_EXT         .ASCII_W "map: extents "
T_S_STATS       .ASCII_W "stats "
T_S_READS       .ASCII_W " block reads "
T_S_RECS        .ASCII_W "records "
T_S_PASS        .ASCII_W "RESULT: PASS\n"
T_S_FAILED      .ASCII_W "RESULT: FAIL count "
T_S_FAIL        .ASCII_W "FAIL rec "
T_S_GOT         .ASCII_W " got "
T_S_EXP         .ASCII_W " exp "
T_S_POS         .ASCII_W " pos "
